services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    image: sapumal001/sumesh-store-backend:latest
    container_name: backend_container
    ports:
      - "5000:6001"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/Sumesh_Store
    volumes:
      - ./backend:/app
      - /app/node_modules  # Fixed path

  frontend:
    image: sapumal001/sumesh-store-frontend:latest
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Fixed path

volumes:
  mongo_data:
