services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/test
    volumes:
      - ./backend:/app
      - /backend/node_modules

  frontend:
    build: ./frontend
    container_name: frontend_container
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /frontend/node_modules

volumes:
  mongo_data:
